[tox]
skipsdist = true
envlist = lint, type, test
skip_missing_interpreters = true

[testenv]
basepython = python3.11
setenv =
    PYTHONPATH = {toxinidir}
    TEST_MODE = 1

[testenv:lint]
basepython = python3.11
usedevelop = false
setenv =
    PYTHONHASHSEED = 0
deps =
    black>=24.4.0
    flake8>=7.0.0
    isort>=5.13.0
commands =
    black --check {posargs:.}
    isort --check {posargs:.}
    flake8 {posargs:eidolon/}

[testenv:type]
basepython = python3.11
deps =
    mypy>=1.9.0
commands =
    mypy --show-error-codes --config-file {toxinidir}/pyproject.toml \
        {posargs:eidolon/}

[testenv:test]
basepython = python3.11
deps =
    pytest>=8.0.0
    pytest-asyncio>=0.23.0
commands =
    pytest {posargs:tests/}

[coverage:report]
show_missing = true
skip_covered = true
skip_empty = true
precision = 2
